area: Serverless Systems 

chairs:

- name: Mohammad Shahrad
  affiliation: 
  webpage: https://mshahrad.github.io/
  orcid: 
  twitter: 

- name: Neeraja J. Yadwadkar
  affiliation: 
  webpage: https://cs.stanford.edu/~neeraja/
  orcid: 
  twitter: 

board:

- name: Cristina Abad
  affiliation: ESPOL University in Guayaquil, Ecuador
  webpage: https://sites.google.com/fiec.espol.edu.ec/cv-cabad/english
  orcid: 
  twitter: 

- name: Rodrigo Fonseca
  affiliation: Brown University and Microsoft Research
  webpage: http://cs.brown.edu/~rfonseca/
  orcid: 
  twitter: 

- name: Inigo Goiri
  affiliation: Microsoft Research
  webpage: https://www.microsoft.com/en-us/research/people/inigog/
  orcid: 
  twitter: 

- name: Nikolas Herbst
  affiliation: University of Würzburg
  webpage: https://scholar.google.de/citations?user=QGov3HoAAAAJ&hl=en
  orcid: 
  twitter: 

- name: Anurag Khandelwal
  affiliation: Yale University
  webpage: http://anuragkhandelwal.com/
  orcid: 
  twitter: 

- name: Bhuvan Urgaonkar
  affiliation: Pennsylvania State University
  webpage: https://www.eecs.psu.edu/departments/directory-detail-g.aspx?q=BUU1
  orcid: 
  twitter: 

- name: Wes J. Lloyd
  affiliation: University of Washington - Tacoma
  webpage: https://faculty.washington.edu/wlloyd/
  orcid: 
  twitter: 

- name: Prateek Sharma
  affiliation: Indiana University
  webpage: http://homes.sice.indiana.edu/prateeks/
  orcid: 
  twitter: 
